language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_install:
  - rustup component add clippy-preview

script:
  - cargo build --verbose
  - cargo clippy -- -D warnings

cache: cargo
